# Site settings
title: Ramnivas Laddad
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ramnivas.com" # the base hostname & protocol for your site
twitter_username: ramnivas
github_username:  ramnivas

markdown: redcarpet

main_site: http://ramnivas.com
blog_root_site: http://blog.ramnivas.com

name: Ramnivas Laddad

avatar: https://secure.gravatar.com/avatar/6dbd84e94f766cd9d9db9fe3cd8804a7
